version: "3.8"

services:
  database:
    image: postgres:latest
    container_name: postgreSQLMulti
    environment:
      POSTGRES_USER: tingeso
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: creditadmin-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data: