version: "3.8"
services:
  backend:
    container_name: creditapp-backend
    image: benjaminmoya/creditapp-backend:latest
    ports:
      - "8090:8090"
    environment:
      - DB_HOST=192.168.1.104
      - DB_PORT=5432
      - DB_USER=tingeso
      - DB_PASS=1234
      - DB_NAME=creditadmin-db
    deploy:
      restart_policy:
        condition: on-failure
