pipeline {
    agent any

    environment {
        SSH_CREDENTIALS_ID = "vm-credentials" 
    }

    stages {
        stage('Deploy to Azure VM') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/BenjaminMoya/tingeso-ev1']])
                sshagent(credentials: [SSH_CREDENTIALS_ID]) {
                sh '''
                    ssh -o StrictHostKeyChecking=no azureuser@20.201.118.55 << 'EOF'
                    cd MVCompose/
                    sudo docker stop $(docker ps -aq)
                    sudo docker-compose pull
                    sudo docker-compose up -d
                    EOF
                '''
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment completado exitosamente'
        }
        failure {
            echo 'Deployment fallido'
        }
    }
}